- docs/AboutUs.md
Change AboutUs.md to include members information.
> Update AboutUs.md (Hao Zhe)

- .gitignore
- src/main/java/student/Student.java
- src/main/java/university/University.java
- src/main/java/university/UniversityRepository.java
Added Student and University package
> Add Student and University Package

- src/main/java/Command/AddCommand.java
- src/main/java/Command/AllocateCommand.java
- src/main/java/Command/Command.java
- src/main/java/Command/DeleteCommand.java
- src/main/java/Command/ExitCommand.java
- src/main/java/Command/GenerateCommand.java
- src/main/java/Command/HelpCommand.java
- src/main/java/Command/ListCommand.java
- src/main/java/parser/Parser.java
- src/main/java/ui/UI.java
- Add, Delete, Help, List, Exit, Generate, Allocate Commands are added for better command controls.
- Pseudo Ui functions are in-place for future developments of StudentList manipulation.
Fix #21
> Add Command Package and Classes

- src/main/java/command/AllocateCommand.java
- src/main/java/studentlist/StudentList.java
- src/main/java/ui/UI.java
- Call `allocate` in `AllocateCommand`
- Run `printAllocatingMessage` and `allocate' concurrently
- Optimise `printAllocatingMessage` 
- Fix `students` in `StudentList` not getting allocated
Close #34
> Integrate allocate algorithm into allocate command

- src/main/java/command/UnknownCommand.java
- src/main/java/parser/Parser.java
Close #36 
- Added UnknownCommand to handle commands that are unrecognised.
> Add new unknown command

- src/test/java/findoursep/AllocatorTest.java
Add JUnit test for Allocator class
Run ``./gradlew.bat build``, the following result will appear in ``tp/build/reports/tests/test/index.html``.
> Allocator JUnit Test

- src/main/java/allocator/Allocator.java
- src/main/java/findoursep/FindOurSEP.java
- src/main/java/parser/Parser.java
- src/main/java/studentlist/StudentList.java
- src/main/java/ui/UI.java
- src/test/java/parser/ParserTest.java
- src/test/java/studentlist/StudentListTest.java
Parser:
`Add`, `Delete`, `Exit`, `Help` and `Unknown` commands were tested and check correct.
StudentList:
`addStudent`, `deleteStudent`, `sortStudentsByGPA`, `sortStudentsById` and `makeStudent` were tested and check correct.
Close #42
> Add JUnit testing for Parser and StudentList Classes

- src/main/java/findoursep/FindOurSEP.java
- src/test/java/ui/UITest.java
- Fix comment that still mentioned `duke` in main class
- Add unit testing for UI class
Tested response printers: `printResponse`, `getUserInput`, `sayHi`, `cleanupAndExit`, `printAllocatingMessage`,
Table printers: `printStudentList`,`generateReport` were ignored as it was proven to be outrageous to compare garbage to garbage 😡 😡
> Add JUnit testing for UI class

- src/test/java/student/StudentTest.java
- src/test/java/university/UniversityTest.java
Tests were done on the constructors and all the functions provided in the packages
> JUnit for Student and University package

- src/test/java/studentlist/StudentListTest.java
close #46 
Added tests for exceptions thrown when:
Adding student format/order is invalid
Student Id format is invalid (Not an uppercase alphabet, followed by 7 digits, followed by another uppercase alphabet)
Gpa format is invalid (Not a float or more than 2 decimal places)
Preferences format is invalid (Rankings not enclosed in curly braces, or are not numbers)
Gpa is out of range (Not in between 0 and 5)
Preference rankings out of range (Not in between 1 and 92)
Added a test when there are spaces in between a student id.
> Add JUnit testing for StudentList class

- src/main/java/command/ListCommand.java
- src/main/java/parser/Parser.java
- src/main/java/studentlist/StudentList.java
1. Remove printStudentList() from StudentList.
2. Create a private reference to ui in the ListCommand.
3. Pass in the correct arguments to the UI.
Close #56
> Fix ListCommand logic flaw

- src/main/java/allocator/Allocator.java
- src/main/java/command/CriteriaCommand.java
- src/main/java/parser/Parser.java
- src/main/java/studentlist/StudentList.java
- src/test/java/findoursep/AllocatorTest.java
implementation of a criteria requirement, more details at
https://github.com/orgs/AY2425S1-CS2113-W12-2/projects/1/views/1?pane=issue&itemId=84134688&issue=AY2425S1-CS2113-W12-2%7Ctp%7C52
> First Criteria Iteration

- src/main/java/command/Commands.java
- src/main/java/parser/Parser.java
Close #64 
- Successfully replace magic literals for commands to commands part of the Commands Enum.
> Enhancement: Replace commands with Enum

- build.gradle
- docs/UserGuide.md
- docs/team/xiongxinzhuang.md
- src/main/java/command/StatCommand.java
- src/main/java/command/ViewQuotaCommand.java
main changes include:
* Update UG for ``stats`` and ``viewQuota`` commands
* Add PPP file for XXZ
* Enable assertions in build.gradle
* Add some assertions in ``statsCommand`` and ``viewQuotaCommand`` classes
> Enable Assertions in build.gradle & Update UG and PPP

- docs/UserGuide.md
- docs/team/paulktham.md
Added description for:
- Minimum
- Add
- Parts of Quick Start
- Personal PPP
> Paul's contribution to the UG

- data/allocation_results.csv
- data/allocation_results.txt
- src/main/java/exceptions/SEPFormatException.java
- src/main/java/filehandler/FileHandler.java
- src/main/java/findoursep/FindOurSEP.java
- src/main/java/ui/Messages.java
- src/main/java/ui/UI.java
- text-ui-test/EXPECTED.TXT
Close #62 
User can now save and export data out via a csv file. 
Upon exit, user will be prompted if they would like to save their data. Simply input 'yes', then 'csv'.
> Add save CSV Feature

- src/main/java/allocator/Allocator.java
- src/main/java/exceptions/SEPFormatException.java
Fix #109 
Add ``SEPFormatException`` for ``CriteriaCommand``.
> Fix CriteriaCommand bug

- docs/DeveloperGuide.md
main changes include:
* Modify the Table of Content to include Product scope, User stories, NFR, Glossary and Instructions for manual testing
* Add some content for NFR and Glossary
* Provide detailed description of the sequence diagrams ``allocateCommand``, ``statsCommand``, and ``viewQuotaCommand``
* Fix some minor logic bugs
> Enhance Developer Guide

- docs/UserGuide.md
> UserGuide.md: Fix minor grammar error

- docs/DeveloperGuide.md
- docs/UserGuide.md
Fix link anchors for faulty content headers in UG and DG
> Fix formatting issues for UG and DG

- docs/UserGuide.md
- src/main/java/ui/UI.java
> Fix bugs from Dry PE

- src/main/java/studentlist/StudentList.java
close #146 
Inputting "delete" with any uppercase letters will now be handled properly as an exception thrown.
> Fix Delete Bug

- docs/UserGuide.md
Update UG regarding preferences and v2.1.
> Update Ug preferences
